vim.cmd.colorscheme('allworldg-light')
vim.lsp.log.set_level("debug")
require("settings")
require("keymap")
require("plugins")
require("lsp")
require("statusline")
require("tabline")

-- require("nvim-messages")
